### ISSUE TITLE
Request for compatibility/feature

### ISSUE THREAD

**Issue by Efimero** [Owlchemist/toggleable-readouts#1]
This other mod [https://steamcommunity.com/sharedfiles/filedetails/?id=2615407383](url) changes the readout to count the materials in blueprints and frames to deduct the requested amount form the stocks count.
Could you look into making your mod available for such a patch or maybe just incorporating the function?

**Comment by Owlchemist** [comment]
Sure, I could look into it.

**Comment by Owlchemist** [comment]
Changes made on their end already
